### ISSUE TITLE
How to skip an stage on new build

### ISSUE THREAD

**Issue by gregorypilar** [dmitryserbin/azdev-release-orchestrator#101]
Hi!

I have a pipeline with two stages:  Green stage, Blue stage

If I use the task like this : 

```yml
  - task: releaseorchestrator@3
    displayName: infra-bicep
    inputs:
      endpointType: 'integrated'
      projectName: 'Dev'
      definitionName: 'infra'
      strategy: 'new'
      branchName: 'main'
      skipTracking: true
      updateInterval: 5
      stageStartAttempts: 10
      stageStartInterval: 60
      approvalInterval: 60
      approvalAttempts: 10
```
It works it calls the infra pipeline a runs both stages

But If I want Only to run one stage,  Green stage, 
```yml
  - task: releaseorchestrator@3
    displayName: infra-bicep
    inputs:
      endpointType: 'integrated'
      projectName: 'Dev Sandbox'
      definitionName: 'infra-bicep'
      strategy: 'new'
      stages: 'Green Stage'
      branchName: 'main'
      skipTracking: true
      updateInterval: 5
      stageStartAttempts: 10
      stageStartInterval: 60
      approvalInterval: 60
      approvalAttempts: 10

```

I got this error :

` Failed retrying <queueRun> for <10> times. Error: 'Deploy Blue stage' is not a valid stage to skip.`

Any Idea why this could be happening?
