### ISSUE TITLE
Possible Bug: Orchestrated pipelines are always triggered using default branch, not the branch the orchestrator pipeline is run from

### ISSUE THREAD

**Issue by sit-md** [dmitryserbin/azdev-release-orchestrator#104]
Title says it all: orchestrated pipelines are always triggered using default branch, not the branch the orchestrator pipeline is run from.

Expectation: run the orchestrated pipelines from the same branch as the orchestrator.

**Comment by josh-casey** [comment]
I ran into this issue as well - also found that it doesn't like when you use branch folders. 

To get around this, just passed the Build.SourceBranch var with refs/heads/ stripped like below:

```
- task: releaseorchestrator@3
  displayName: 'Build Pipeline'
  inputs:
    projectName: 'Project'
    definitionName: 'Build Service'
    strategy: 'new'
    branchName: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/') }}
```
