### ISSUE TITLE
Feature request: Copy artifact version from current release definition

### ISSUE THREAD

**Issue by JoostvdB94** [dmitryserbin/azdev-release-orchestrator#47]
Rather than specifying a filter to define what artifacts to use when running a new release, it would be helpful to specify the artifacts to use directly in the release that is running the release orchestrator task.

Certainly in our case this would be helpful as we are not tagging our artifacts. 

Please consider adding this feature

**Comment by dmitryserbin** [comment]
Hi, thanks for the feedback.

Just trying to get my head around this. Do you want to be able to specify/filter target pipeline build artifact version by name in the orchestrator task? I.e. something like:

```yaml
- task: releaseorchestrator@2
  displayName: Create release
  inputs:
    projectName: My-Project
    definitionName: My-Release
    artifactVersionFilter: true
    artifactName: My-Build
    artifactVersion: My-Build-20190521.4
```

![image](https://user-images.githubusercontent.com/30379061/93300302-a3f17480-f84a-11ea-94e3-eab1ba271f1b.png)
