### ISSUE TITLE
V3 task with parameters fails Contribution/HierarchyQuery API call

### ISSUE THREAD

**Issue by nickwheeler-wwt** [dmitryserbin/azdev-release-orchestrator#74]
Hello,

I'm having an issue implementing the V3 task with parameters specifically within an integrated project (my repos/pipelines are in the same azdo project). Without parameters, my child target pipeline triggers successfully and everything works wonderfully. With parameters, the call to get the target pipelines parameters times out after 10 attempts with the same message:

```
2022-05-11T16:17:31.754Z release-orchestrator:Retry:retryAsync Error: Unable to retrieve <policy> (63) run parameters
    at BuildWebApiRetry.getRunParameters (/home/vsts/work/_tasks/releaseorchestrator_5d38d46b-4c0a-4c14-8f0c-04df59e4dc27/3.0.1592/extensions/buildwebapiretry/buildwebapiretry.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2022-05-11T16:17:41.764Z release-orchestrator:ApiClient:post Making <[https://dev.azure.com/<redacted>//_apis/Contribution/HierarchyQuery/project/<redacted>](https://dev.azure.com/<redacted>//_apis/Contribution/HierarchyQuery/project/<redacted>) API <POST> call
2022-05-11T16:17:41.874Z release-orchestrator:BuildWebApiRetry: { dataProviderExceptions:
   { 'ms.vss-build-web.pipeline-run-parameters-data-provider':
      { exceptionType: 'ResourceValidationException',
        message:
         'The repository policy in project <redacted> could not be retrieved. Verify the name and credentials being used.',
        stackTrace: null } },
  dataProviderSharedData:
   { _featureFlags: { 'Build2.DisableRunTimeVariableEdit': false } },
  dataProviders:
   { 'ms.vss-web.component-data': {},
     'ms.vss-web.shared-data': null } }
```
After 10 tries:

```
##[error]Failed retrying <getRunParameters> for <10> times. Error: Unable to retrieve <policy> (63) run parameters
```

Here is the code block from pipeline:
```
  - stage: policyPipe
    displayName: Initiate Policy Pipeline
    condition: |
      and(
        eq(variables['Build.Reason'], 'Manual'),
        eq('${{ parameters.initateAllPipes }}', 'true')
      )
    jobs:
    - job:
      steps:
      - task: releaseorchestrator@3
        displayName: Kickoff pipeline 
        inputs:
          projectName: $(System.TeamProject)
          definitionName: policy
          branchName: ${{ parameters.policyRefName }}
          strategy: new
          parameters: applyTerraform=${{ parameters.applyTerraform }}
```

Verified that our build service has all the requisite permissions per your v3 docs. Again, everything works like a charm without parameters specified.

**Comment by nickwheeler-wwt** [comment]
I should note that I can execute the same call for `ms.vss-build-web.pipeline-run-parameters-data-provider` targeting the same branch on my target kickoff repo and get a good return with the parameters block containing the parameter I am expecting to see.

**Comment by dmitryserbin** [comment]
Thanks for reporting this. Let me take a look and get back to you soon.

**Comment by fogartyp** [comment]
Seeing the same issue. 

Set up an ADO project to develop a POC using the Release Orchestrator V3. Receiving the following time-out error when attempting to use parameters.

`##[error]Failed retrying <getRunParameters> for <10> times. Error: Unable to retrieve <pipeline1> (1) run parameters`

Single Project two repos/pipelines.

**Controller Project/Pipeline**
```
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: releaseorchestrator@3
  displayName: Release Orchestrator
  inputs:
    projectName: dotnet
    definitionName: dotnet
    strategy: new
    parameters: |
      MyParameter=MyRemoteValue
```

**Target Project/Pipeline**
```
parameters:
- name: MyParameter
  type: string
  default: 'MyLocalValue'

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 'Echo'
    displayName: 'Echo'
    jobs:
      - job: 'Echo'
        steps:
        - script: echo ${{ parameters.MyParameter }}
  - stage: Dotnet
    displayName: 'Dotnet'
    jobs:
      - job: 'Dotnet'
        steps:
        - script: dotnet build --configuration $(buildConfiguration)
```

Followed the instructions above setting top (all) level permissions for the **Build Service** user. Went ahead and gave all perms.

```
dotnet Build Service (xyzabc)
Administer build permissions - Allow
Delete build pipeline - Allow
Delete builds - Allow
Destroy builds - Allow
Edit build pipeline - Allow
Edit build quality - Allow
Manage build qualities - Allow
Manage build queue - Allow
Override check-in validation by build - Allow
Queue builds - Allow
Retain indefinitely - Allow
Stop builds - Allow
Update build information - Allow
View build pipeline - Allow
View builds - Allow
```

As @nickwheeler-wwt experienced, without parameters the Orchestrator (Controller) pipeline succeeds. Additionally, the Dotnet (Target) pipeline presents the parameter at runtime if executed manually.

Thank you.
